### ISSUE TITLE
CFD 交易明細的小視窗

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#119]
#### Opinion
- scheduled closed 的時間沒有顯示在交易明細上
- state: open close 的設計容易混淆
-----
#### 更改 Interfaces
```tsx
// ICFDDetails
  recommendedTp: number; // 推薦的 takeProfit 點位
  recommendedSl: number;
  guranteedStopFee: number; // 保證止損費用
```

```tsx
// Market
  guranteedStopFee: number; // 保證止損費用

```

-----
- [x]  UI of changes of guaranteed stop checked state
    - [x]  toggle 灰色
    - [x]  toggle disabled
    - [x] 圓圈灰色
- [x]  timestamp 拆成日期跟時間
- [x] padStart 補零
- [x] debug: get Toggle state and display input responsively
- [x] openCfdDetails?: IOpenCFDDetails; 測試
- [x] Pass upperLimit = Infinity AND set optional in TradingInput #165 
- [x]  data structure the same as `interfaces`
- [x]  pass data from OpenSubTab, which comes from context #163 
- [x] 點整個 position item 顯示調整倉位的視窗
- [x] #183
- [x] Guaranteed stop 
  - [x] 可以事後打勾，但打勾並且送出update請求後就不能取消
  - [x] 不能調整停損點 #165 
  - [x] 一開始就打勾的話 input 不能調整
  - [x] 打勾之後但還沒送出update請求， input 可以調整
  - [x] 沒有保證止損點位
- [x]  popping up position modal from position item
- [x]  modal layout
- [x] constants of colors organized
- [x] position, border color, pnl color 切換
- [x] limit / stop 
- [x] guranteedStopAt 的欄位
- ~保證止損取消之後，止損點位要恢復成用戶上一個輸入的值~
- [x] 送出更新請求之前要比對用戶更新了哪些值
- [x] toast
- random dummy data
- #175
- [x] [mark the code](https://github.com/CAFECA-IO/TideBit-DeFi/pull/196#discussion_r1098495780)
-----
- [x]  PositionDetailsModal 有更新才能按按鈕，否則就 disabled
- [x]  PositionDetailsModal 按更新後要 disabled (並整個消失 #195 )，再執行 function 內容
- [x] 清理無效的 comments
- [x] Solve the conflict when merging into `develop`
-----
Ref: 
- 設計稿
  - [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/screen/1efeff4c-2c35-4644-aa82-40fd9e9bf9fe/specs/)
  - [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/screen/52e1328b-a83e-4c59-a3be-f5ca82af482f)
- Sequence Diagram
  - [Sequence Diagram 001 (interaction between user, frontend and backend)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00001.md)
  - [Sequence Diagram 002 (background mechanism)](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md)
- Diagrams
  - [Component Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCP00001.md)
  - [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
  - [Use Cases Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDUC00001.md)

**Comment by arealclimber** [comment]
taking 8 hrs
remaining 5 hrs

**Comment by arealclimber** [comment]
taking 2 hrs
remaining 4 hrs

**Comment by arealclimber** [comment]
taking 6 hrs

**Comment by arealclimber** [comment]
taking 5 hrs

**Comment by arealclimber** [comment]
taking 3 hrs
remaining 2 hrs

**Comment by arealclimber** [comment]
taking 3 hrs

**Comment by arealclimber** [comment]
taking 0.5 hrs
remaining 2.5 hrs
- Trading Input `onChange`

**Comment by arealclimber** [comment]
taking 6 hrs
