### ISSUE TITLE
修正現有的 userContext 與 squence diagram 及 class diagram 的差異

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#209]
- [x] 確認目前進度，需要確認的有
- [x] 01-app-init
  - [x] Use Case: 03 連結電子錢包
    - [x] 041-wallet-connect 
    - [x] 042-sign-service-term
  - [x] 06 查看個人資產明細
    - [x] 043-user-start
  - [x] 031-create-order
  - [x] 032-CFD-update-and-close
  - [x] 032-transaction-process:Layer 1
  - [x] 033-transaction-process:Layer 2

- [x] 調整差異
    - [01-app-init](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#01-app-init)
    - [x] Add OrderEngine
      - [x] [031-create-order](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#031-create-order)
      - [x] [032-CFD-update-and-close](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#032-CFD-update-and-close)
    - [x] [041-wallet-connect](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#041-wallet-connect)
    - [x] [042-sign-service-term](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#042-sign-service-term)
    - [x] [043-user-start](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#043-user-start)
    - [x] [044-wallet-disconnect](https://github.com/CAFECA-IO/Documents/edit/main/TBD/TBDSD00002.md#044-wallet-disconnect)
    - [x] [032-transaction-process:Layer 2](https://github.com/CAFECA-IO/Documents/edit/main/TBD/TBDSD00002.md#033-transaction-process-layer-1)
    - [x] [033-transaction-process:Layer 2](https://github.com/CAFECA-IO/Documents/edit/main/TBD/TBDSD00002.md#033-transaction-process-layer-2)

- [x] 補齊 userContext 功能
Ref:
  - Diagrams:
    - [squence diagram 02](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#041-wallet-connect)
    - [Class Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDCD00001.md)
    - [Use Cases Diagram](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDUC00001.md)

## 補充：
  - [042-sign-service-term](https://github.com/CAFECA-IO/Documents/blob/main/TBD/TBDSD00002.md#042-sign-service-term) => 等 @arealclimber 將 wallet_pannel 改好後還要再調整

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by TzuHanLiang** [comment]
- take 3hrs

**Comment by TzuHanLiang** [comment]
- take 2hrs

**Comment by TzuHanLiang** [comment]
- take 1hrs

**Comment by TzuHanLiang** [comment]
- take 1.5hrs add constant
  - type ITrend = 'UP' | 'DOWN' | 'EQUAL';
  - type IOrderState = 'OPENING' | 'CLOSED';
  - type ICFDClosedType = 'SCHEDULE' | 'FORCED_LIQUIDATION' | 'STOP_LOSS' | 'TAKE_PROFIT' | 'BY_USER';
