### ISSUE TITLE
TideBit DeFi Development

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/TideBit-DeFi#3]

**Comment by arealclimber** [comment]
Tools: 
Toast
https://github.com/timolins/react-hot-toast
https://github.com/fkhadra/react-toastify

**Comment by arealclimber** [comment]
### 2022-11
- [x] CAFECA-IO/TideBitEx#1035
- [x] CAFECA-IO/TideBit-DeFi#1
- [x] CAFECA-IO/KnowledgeManagement#7
- [x] CAFECA-IO/TideBit-DeFi#11
- [x] CAFECA-IO/TideBit-DeFi#21
- [ ] CAFECA-IO/KnowledgeManagement#8
- [x] 實作首頁 Landing page 電腦版
  - [x] CAFECA-IO/TideBit-DeFi#2
  - [x] CAFECA-IO/TideBit-DeFi#5
  - [x] CAFECA-IO/TideBit-DeFi#6
  - [x] CAFECA-IO/TideBit-DeFi#17
  - [ ] #39
- [ ] 實作首頁 Landing page 手機板
  - [x] CAFECA-IO/TideBit-DeFi#30
- [ ] 實作錢包畫面
  - [x] CAFECA-IO/TideBit-DeFi#10
  - [x] CAFECA-IO/TideBit-DeFi#12
   - [x] CAFECA-IO/TideBit-DeFi#18
  - [x] CAFECA-IO/TideBit-DeFi#24
  - [x] CAFECA-IO/TideBit-DeFi#25
  - [x] CAFECA-IO/TideBit-DeFi#26 
  - [x] CAFECA-IO/TideBit-DeFi#35
- [ ] 實作錢包功能 Metamask & Walletconnect
  - [x] CAFECA-IO/TideBit-DeFi#13
  - [ ] CAFECA-IO/TideBit-DeFi#14
  - [ ] CAFECA-IO/TideBit-DeFi#15
  - [ ] CAFECA-IO/TideBit-DeFi#27
### 臨時新增目標:
- [x] CAFECA-IO/TideBit-DeFi#29
- [x] CAFECA-IO/TideBit-DeFi#30


參考資料: 
- [TideBit DeFi 設計稿電腦版 Spec](https://xd.adobe.com/view/920d36bd-2d1a-4edd-8a2a-824445f1d3b0-c75e/specs/)
- [TideBit DeFi 設計稿手機版 Spec](https://xd.adobe.com/view/b4bc1f81-78f4-4de9-979f-20cb0d457d70-e1ef/)

**Comment by arealclimber** [comment]
### December 2022
- [x] CAFECA-IO/TideBit-DeFi#15
- [x] CAFECA-IO/TideBit-DeFi#14
- [x] CAFECA-IO/TideBit-DeFi#45
- [x] CAFECA-IO/TideBit-DeFi#43
- [x] CAFECA-IO/TideBit-DeFi#47
- [x] CAFECA-IO/TideBit-DeFi#44
- [x] CAFECA-IO/TideBit-DeFi#49
- [x] #74
- [x] #72

**Comment by arealclimber** [comment]
**[January 2023](https://github.com/CAFECA-IO/EventReport/blob/main/2023/m01/Shirley.md)**

- [x]  [Trading Page - Trading Header + Ticker selector box modal 電腦版 #82](https://github.com/CAFECA-IO/TideBit-DeFi/issues/82) - 8 points
- [x]  [trade tab - 暫停交易 & 尚未登入畫面 #104](https://github.com/CAFECA-IO/TideBit-DeFi/issues/104) - 2 points
- [x]  [position tab - 尚未登入 UI #116](https://github.com/CAFECA-IO/TideBit-DeFi/issues/116) - 1 point
- [x]  [button ripple effect #94](https://github.com/CAFECA-IO/TideBit-DeFi/issues/94) - 3 points
- [x]  [open position item 水平線位置 #139](https://github.com/CAFECA-IO/TideBit-DeFi/issues/139) - 1 points
- [x]  [Context Provider refactor #130](https://github.com/CAFECA-IO/TideBit-DeFi/issues/130) - 3 points
- [x]  [the same design between light and dark mode #137](https://github.com/CAFECA-IO/TideBit-DeFi/issues/137) - 1 points
- [x]  [Theme Context (偵測螢幕寬度) #111](https://github.com/CAFECA-IO/TideBit-DeFi/issues/111) - 5 points
- [x]  [data of `User Overview` from User context #141](https://github.com/CAFECA-IO/TideBit-DeFi/issues/141) - 1 points
- [x]  [出金&入金流程的小視窗 #105](https://github.com/CAFECA-IO/TideBit-DeFi/issues/105) - 5 points
- [x]  [table of data structure of interface #144](https://github.com/CAFECA-IO/TideBit-DeFi/issues/144) - 3 points
- [x]  [Trading Page - 多空比實時數據圖 電腦版+行動版 #84](https://github.com/CAFECA-IO/TideBit-DeFi/issues/84) - 3 points
- [x]  [Trading Page - 簡介區跟文章區 電腦版+行動版 #85](https://github.com/CAFECA-IO/TideBit-DeFi/issues/85) - 3 points
- [x]  [整理交易相關的 context 所需資料 #114](https://github.com/CAFECA-IO/TideBit-DeFi/issues/114) - 2 points
- [x]  [整理 interface #149](https://github.com/CAFECA-IO/TideBit-DeFi/issues/149) - 1 points
- [x]  [KM - Typescript Tips WorkGuidelines#15](https://github.com/CAFECA-IO/WorkGuidelines/issues/15) - 8 points
- [x]  [KM - Shirley's Tips #145](https://github.com/CAFECA-IO/WorkGuidelines/issues/20) - 3 points

**Comment by arealclimber** [comment]
### February 2023

[月報](https://github.com/CAFECA-IO/EventReport/blob/main/2023/m02/Shirley.md)

[第五周](https://github.com/CAFECA-IO/EventReport/blob/main/2023/w05/Shirley.md)
- [x] CAFECA-IO/WorkGuidelines#15
- [x] #163
- [x] CAFECA-IO/WorkGuidelines#20
- [x] #165
- [x] #183 
-----
第六周
- [x] #157
- [x] #199
- [x] #198
- [x] #211
- [ ] CAFECA-IO/TideBit-DeFi#120
- [x] CAFECA-IO/TideBit-DeFi#115
- [ ] CAFECA-IO/TideBit-DeFi#119
- [x] #195
- [x] #164
- [ ] CAFECA-IO/TideBit-DeFi#106
- [ ] #161
- [x] #192 
- [x] #194
-----
第七周
-----
- [ ] #162
- [ ] #216 
- [ ] PositionUpdatedModal
- [ ] i18n in TradeTab
- [ ] i18n in PositionTab
- [ ] i18n in MarketSection
- [ ] #197
- [ ] CAFECA-IO/TideBit-DeFi#73
- [ ] CAFECA-IO/TideBit-DeFi#121
- [ ] CAFECA-IO/TideBit-DeFi#125
- [ ] #48 
- [ ] CAFECA-IO/TideBit-DeFi#132
- [ ] CAFECA-IO/WorkGuidelines#16
- [ ] CAFECA-IO/TideBit-DeFi#57
- [ ] CAFECA-IO/TideBit-DeFi#107
- [ ] CAFECA-IO/TideBit-DeFi#150
- [ ] #158
- [ ] CAFECA-IO/KnowledgeManagement#11
- [ ] CAFECA-IO/TideBit-DeFi#124
- [ ] CAFECA-IO/TideBit-DeFi#109
- [ ] CAFECA-IO/TideBit-DeFi#108
- [ ] CAFECA-IO/TideBit-DeFi#126
- [ ] refactored by using data of `user` context and `market` context in components
- [ ] #155
- [ ] CAFECA-IO/TideBit-DeFi#62
- [ ] CAFECA-IO/TideBit-DeFi#63
- [ ] #168
- [ ] #170
- [ ] #169
- [ ] #279
- [ ] #280
- [ ] #281
- [ ] #282
- [ ] #283
- [ ] #284
- [ ] #286
- [ ] #287
- [ ] #288
- [ ] #289
- [ ] #290
 

### New added
- [ ] #171
- [ ] #172
- [x] #181
- [ ] #189
- [ ] #202
- [ ] #208
- [ ] #213
- [ ] #215
- [ ] #220
- [x] #221
- [x] #230
- [ ] #231
- [ ] #232
- [ ] #234
- [ ] #235
- [ ] #240
- [ ] #241
- [ ] #242
- [x] #244 
- [ ] #259
- [x] #261 
- [ ] #263
- [x] #267
- [ ] #269
- [ ] #271 
- [ ] #272
- [ ] #273
- [ ] #274
- [ ] #275
-----
- #173 
-

**Comment by arealclimber** [comment]
## 2023/03-2023/04 

- [x] #466
- [x] #487
- [x] #489
- [ ] #493
- [x] #500
- [x] #521
- [x] #522
- [x] #524
- [ ] #525
- [ ] #527
- [x] #528
- [ ] #530
- [x] #536
- [ ] #537
- [ ] #538
- [x] #295
- [x] #297
- [x] #311
- [ ] #314
- [x] #317
- [ ] #318
- [x] #326
- [ ] #327
- [x] #335
- [ ] #343
- [x] #345
- [x] #352
- [x] #353
- [ ] #364
- [x] #366
- [ ] #374
- [ ] #375
- [ ] #376
- [x] #378
- [x] #379
- [x] #380
- [x] #381
- [x] #382
- [x] #384
- [x] #402
- [ ] #403
- [x] #405
- [ ] #414 
- [x] #425
- [ ] #428
- [x] #429
- [ ] #431
- [ ] #432
- [x] #433
- [x] #434
- [ ] #435
- [ ] #436
- [ ] #437
- [ ] #438
- [ ] #439
- [ ] #440
- [ ] #441
- [ ] #442
- [ ] #443
- [ ] #444
- [ ] #445
- [ ] #446
- [ ] #447




-----
### March 2023

- [ ] #162
- [ ] i18n in TradeTab
- [ ] i18n in PositionTab
- [ ] i18n in MarketSection
- ~#197~
- [x] CAFECA-IO/TideBit-DeFi#73
- [ ] CAFECA-IO/TideBit-DeFi#121
- [ ] CAFECA-IO/TideBit-DeFi#125
- [ ] #48 
- [ ] CAFECA-IO/TideBit-DeFi#132
- [ ] CAFECA-IO/WorkGuidelines#16
- [ ] CAFECA-IO/TideBit-DeFi#57
- [x] CAFECA-IO/TideBit-DeFi#107
- [ ] CAFECA-IO/TideBit-DeFi#150
- [x] #158
- [ ] CAFECA-IO/KnowledgeManagement#11
- [ ] CAFECA-IO/TideBit-DeFi#124
- [ ] CAFECA-IO/TideBit-DeFi#109
- [ ] CAFECA-IO/TideBit-DeFi#108
- [ ] CAFECA-IO/TideBit-DeFi#126
- [ ] #155
- [x] CAFECA-IO/TideBit-DeFi#62
- [x] CAFECA-IO/TideBit-DeFi#63
- [x] #170
- [ ] #169
- [ ] #279
- [ ] #280
- [ ] #291
- [ ] #292
- [ ] #293
- [ ] #281
- [ ] #282
- [ ] #283
- [ ] #284
- [x] #286
- [x] #287
- [x] #288
- [ ] #289
- [ ] #290
-----
- [x] #171
- [x] #172
- [x] #189
- [ ] #202
- [ ] #213
- [x] #215
- [ ] #220
- [ ] #231
- [ ] #232
- [ ] #234
- [ ] #235
- [ ] #240
- [ ] #241
- [ ] #242
- [ ] #263
- [ ] #269
- [ ] #271 
- [ ] #272
- [ ] #273
- [ ] #274
- [ ] #275
-----
