### ISSUE TITLE
根據 alpha milestone 整理後端的點數

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/TideBit-DeFi#470]
- [ ] [首頁： 網站儲備、tickers: ETH & BTC、用戶數量]
 - [ ] [整理 tickerLiveStatics]
 - [ ] [整理 ticker 介紹]
 - [ ] [登入使用 metamasj + JWT token、要紀錄到 histories]
 - [ ] [交易環節： 拿報價單、建議停損及停利]
 - [ ] [交易環節： CREATE、UPDATE、CLOSE CFD 簽名後寫進DB]
 - [ ] [用戶行為要紀錄到 DB
 - [ ] [提供 interest API]
 - [ ] [dummy deposit: 2000 USDT/month 要紀錄到 histories]
 - [ ] [實時更新 ITickerData 裡面的 lineGraphProps]
 - [ ] [candlestickData 新增補值及clean data的功能]

**Comment by TzuHanLiang** [comment]
- take 3hrs
# TBD backend: 49 points
 [使用 NestJs 作為 TBD 的 backend #472](https://github.com/CAFECA-IO/TideBit-DeFi/issues/472) - 5 points
 [整合 mongodb 到 NestJs 作為 TBD 的資料庫 #473](https://github.com/CAFECA-IO/TideBit-DeFi/issues/473) - 5 points
 [在 TBD nestJS 專案中串接 OKX websocket #474](https://github.com/CAFECA-IO/TideBit-DeFi/issues/474) - 3 points
 [在 TBD nestJS 專案中串接 OKX API #475](https://github.com/CAFECA-IO/TideBit-DeFi/issues/475) - 3 points
 [建立 table 並提供 CRUD #484](https://github.com/CAFECA-IO/TideBit-DeFi/issues/484) - 8 points
 [登入使用 metamask + JWT token 並紀錄到 DB #476](https://github.com/CAFECA-IO/TideBit-DeFi/issues/476) - 3 points
 [入金功能: 每個用戶每月可以領 2000 USDT 在 TBD 內部使用 #477](https://github.com/CAFECA-IO/TideBit-DeFi/issues/477) 2 points
 [交易環節： 拿報價單、建議停損及停利的 API #478](https://github.com/CAFECA-IO/TideBit-DeFi/issues/478) - 3 points
 [首頁及交易環節： 提供拿交易對的 API #479](https://github.com/CAFECA-IO/TideBit-DeFi/issues/479) - 5 points
 [使用 DB 的資料提供 API 給前端用在首頁的資訊： 網站儲備、用戶數量、實時交易量 #480](https://github.com/CAFECA-IO/TideBit-DeFi/issues/480) - 2 points
 [交易環節： CREATE、UPDATE、CLOSE CFD API #481](https://github.com/CAFECA-IO/TideBit-DeFi/issues/481) - 3 points
 [在 NestJS 專案 API 被呼叫後有提供 signature 的行為需要有驗證 signature 的function #482](https://github.com/CAFECA-IO/TideBit-DeFi/issues/482) - 3 points
 [用戶介面： 提供 interest API #483](https://github.com/CAFECA-IO/TideBit-DeFi/issues/483) - 2 points
 [用戶介面： 提供 histories API #485](https://github.com/CAFECA-IO/TideBit-DeFi/issues/485) - 2 points
 [交易環節： 提供 cfds API #486](https://github.com/CAFECA-IO/TideBit-DeFi/issues/486)  - 2 points
 [交易環節: 提供 tickerLiveStatics API #488](https://github.com/CAFECA-IO/TideBit-DeFi/issues/488) - 3 points

**Comment by TzuHanLiang** [comment]
- (需補上)前端透過pusher 連上後端取得即時資料 - 3points
